name: Bundle with esbuild

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install esbuild

      - name: Run esbuild to bundle the app
        run: npx esbuild index.js --bundle --outfile=dist/bundle.js

      - name: Upload bundled artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundled-web-app
          path: dist/
