name: Bundle with esbuild

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install esbuild

      - name: Run esbuild to bundle js
        run: npx esbuild public/main.js --bundle --outfile=dist/js_bundle.js

      - name: Run esbuild to bundle css
        run: npx esbuild public/style.css --bundle --outfile=dist/css_bundle.css

      - name: Run the inlining script
        working-directory: ${{ github.workspace }}
        run: node inline-scripts-from-files.js

      - name: Upload bundled artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundled-web-app
          path: dist/
